### ISSUE TITLE
Misleading error message when Optimization Toolbox is not installed

### ISSUE THREAD

**Issue by spribitzer** [luisfabib/DeerAnalysis2#1]
I tried to follow the  "Analyzing Datasets"  example in the tutorial section, but whenever I ran
```matlab
[B,lam] = fitbackground(V,t,@td_exp);
```
I received the following error message:

```matlab
Invalid solver specified. Provide a solver name or handle (such as
'fmincon' or @fminunc).
```

After some digging around it turned out, that I did not have the `Optimization Toolbox` installed. However, the error message insinuated that I had not set the paths correctly.

Suggestion: Test for availability of `Optimization Toolbox` with
```matlab
license('test','optimization_toolbox')
```
which returns `1` if the toolbox is installed.

**Comment by luisfabib** [comment]
The program controls the license of the toolbox at the dependent functions and prompts an explanatory error if the toolbox is missing.
