### ISSUE TITLE
RegOp is not passed to selregparam

### ISSUE THREAD

**Issue by spribitzer** [luisfabib/DeerAnalysis2#105]
When calling `fitregparam` with optional arguments, e.g. `fitregmodel(...,'RegOrder',0)`, these optional arguments are not passed to `selregparam` (line 137). Instead an empty `varargin` is passed.  `varargin` is cleared in line 110. There is a comment "Remove used options from varargin so they are not passed to selregparam", but I feel like some arguments, such as RegOrder, should be passed to `selregparam`?

**Comment by luisfabib** [comment]
The new options system has taken care of this. Now options passed to a function will also be properly passed to all nested functions with proper options parsing and validation. 

Issue closed
