### ISSUE TITLE
Link to documentation in README.md not working

### ISSUE THREAD

**Issue by laenan8466** [luisfabib/DeerAnalysis2#114]
The link to the MATLAB DeerLab Doku is not working and gives a 404.
Change
https://github.com/JeschkeLab/DeerLab-Matlab/blob/develop/jeschkelab.github.io/DeerLab-Matlab
to
https://jeschkelab.github.io/DeerLab-Matlab/0.9.2/index.html

**Comment by luisfabib** [comment]
Fixed
