### ISSUE TITLE
multispin effect's future

### ISSUE THREAD

**Issue by luisfabib** [luisfabib/DeerAnalysis2#12]
In the ``supressghost`` function there is no re-scaling as described in the original van Hagens paper

**Comment by luisfabib** [comment]
The re-scaling was not necessary as the program does not necessarily need the dipolar evolution function to fit the data.

**Comment by luisfabib** [comment]
The issue now is whether the ``suppressghost`` function is even needed. The function does only perform a square root operation on the signal. This operation is easier carried out by the user than calling a specialized function with input arguments which does the same thing.

Additionally there are many issues plaguing this "correction" approach, especially when considering the background function, which was not considered in the theory of the original paper. 

Multi-spin effects on one-dimensional dipolar spectroscopy techniques require a revisiting of the theory and its numerical treatment.

**Comment by stestoll** [comment]
I agree that this function should be dropped. However, the manual should mention ghost suppression in an appropriate place.

**Comment by gjeschke** [comment]
I object to some of the statements above. No one ever claimed that this "ghost suppression" was theoretically exact. However, it is still better than not correcting at all. In particular, it is a diagnostic for testing whether there is a multi-spin problem. Empirically, background fits work well with it.

Regarding proper theory for the problem and including it in the kernel: Good luck! An exact solution requires information on geometry of the system.

I can live with not having a specialized function, as long as "ghost suppression" is mentioned in the manual as a (partial) stop-gap solution for multi-spin problems.

**Comment by luisfabib** [comment]
I agree that the theory was never claimed to be exact and has an important application. I apologize if my comment could be interpreted that way. 

I am aware that a full theoretical coverage of multi-spin effects would be tedious and (probably) impossible to generalize in a way that it is still easily applicable. My concern was rather with the state of the background after the square-root conversion, i.e. how multi-spins effects appear on the background and how well they are suppressed by this correction. 

Since we agree that a specialized function is not necessary, my suggestion would be to have a specialized tutorial on the documentation to show how users should perform this correction and refer to the von Hagens paper for detailed information.

**Comment by luisfabib** [comment]
I have been thinking about a new approach for the treatment of multi-spin effects. This idea behind this approach is based on the same theory as the power scaling is based on (namely the von Hagens et al, PCCP, 2013, 15, 5854 paper). So we will be introducing no new theory here. 

First, these are the short-comings of power scaling (according to the original literature): 
-  It is a parametric approach and introduces the power scale as additional parameter. 
-  Even though it can be approximated by 1/(N-1) with N being the number of spins in the system, an exact correction may only be reached for a single orientation and for equivalent observer spins. It also worsens if the spins are not symmetrically equivalent. 
- Quality results limited to small modulation depths. 
- Ghost terms are introduced post-correction.
- Requires prior background correction. 

Additionally, the necessity for "correcting" the signal goes against the main philosophy of DeerLab. Therefore, I propose the follow a different approach based on similar ideas. First let's consider the equations for the form factor derived by von Hagens et al. specifically for the tri-radical case (for the sake of simplicity) 

![CodeCogsEqn](https://user-images.githubusercontent.com/48292540/75050884-2b515200-54cd-11ea-8e7d-5f20d9773f4a.png)


Now, the rational behind the choice of power scaling was argued on the main differences between these two equations, which is the unmodulated constant terms. From this difference, the of power scaling by 1/2 (i.e. taking the square-root) was found.

Now I recognize that due to the non-linear composition of the equation (15) one cannot define a kernel function which will fully describe this signal. However, one can define a kernel which is a good enough approximation of this signal. 

![CodeCogsEqn](https://user-images.githubusercontent.com/48292540/75050713-d281b980-54cc-11ea-94f9-0a20b928f86f.png)

We can see that we can describe the full three-spins signal up to the last term (the three-spin contributions), which is different. This kernel can only produce a term where the same distance distribution/dipolar signal is multiplied by itself. The error introduced by this approximation is given by 

![CodeCogsEqn](https://user-images.githubusercontent.com/48292540/75052720-57ba9d80-54d0-11ea-8022-94aaaf3e8b24.png)

However, the error between these two terms is smaller compared to the error introduced by power scaling as the rest of the signal is modelated accurately. Even further, this model should be exact for symmetrically equivalent spins (i.e. an equilateral triangle geometry).  


![path32170](https://user-images.githubusercontent.com/48292540/75051680-9cddd000-54ce-11ea-950a-3553392a4114.png)

In this figure we can see this deviation for different geometries. As expected, the error of an equilateral geometry is minimal and it increases as the scalene geometry becomes more pronounced.  

This error is still small, compared to the amount of precision achieved by correctly modelling the relative amplitudes of the multi-spin frequency contributions and the un-modulated terms. 
Additionally, this whole approximated kernel is easily generalized for a N-spin system:

 
![CodeCogsEqn](https://user-images.githubusercontent.com/48292540/75052181-75d3ce00-54cf-11ea-9409-66d7a8a344df.png)

This approximation could be easily be built into the ``dipolarkernel`` function with the number of spins ``N`` as the optional  input parameter. 

This is no perfect approach as it still lacks in precision, however, it provides enough precision to model multi-spin effects with a precision which is still within the noise precision. 


So let's compare with the shortcomings of the power scaling approach. The kernel approach now:
-  ~~It is a parametric approach and introduces the power scale as additional parameter.~~
-  ~~Even though it can be approximated by 1/(N-1) with N being the number of spins in the system, an exact correction may only be reached for a single orientation and for equivalent observer spins. It also worsens if the spins are not symmetrically equivalent.~~ 
- Quality results limited to small modulation depths. 
- ~~Ghost terms are introduced post-correction.~~
- ~~Requires prior background correction.~~ 

So the main shortcoming of this method would be the limitation to "small" modulation deppths, otherwise the error term (which is scaled by lambda-squared) can become the dominant factor. 

Comments and thoughts are most appreciated ;)

**Comment by luisfabib** [comment]
We can easily expand the multi-pathway model to an arbitrary multi-spin system. Since the signal is given by a sum over all two-spin combinations over the sum of all pathways of the individual spins added as a product of the modulations. In the case of a triradical it would read:

<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{120}&space;\fn_phv&space;\\\\&space;F_3^{MP}&space;=&space;\sum^3_{i=1}\sum^3_{j\neq&space;i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_mD_i(T_m)D_j(T_n)&space;\\\\&space;\text{which&space;is&space;proportional&space;to}&space;\\\\&space;F_3^{MP}&space;\propto&space;\sum^3_{i=1}\sum^3_{j\neq&space;i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_m&space;\cos(\omega_iT_m)\cos(\omega_jT_n)" target="_blank"><img src="https://latex.codecogs.com/png.latex?\dpi{120}&space;\fn_phv&space;\\\\&space;F_3^{MP}&space;=&space;\sum^3_{i=1}\sum^3_{j\neq&space;i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_mD_i(T_m)D_j(T_n)&space;\\\\&space;\text{which&space;is&space;proportional&space;to}&space;\\\\&space;F_3^{MP}&space;\propto&space;\sum^3_{i=1}\sum^3_{j\neq&space;i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_m&space;\cos(\omega_iT_m)\cos(\omega_jT_n)" title="\\\\ F_3^{MP} = \sum^3_{i=1}\sum^3_{j\neq i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_mD_i(T_m)D_j(T_n) \\\\ \text{which is proportional to} \\\\ F_3^{MP} \propto \sum^3_{i=1}\sum^3_{j\neq i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_m \cos(\omega_iT_m)\cos(\omega_jT_n)" /></a>

where the lambdas are the pathway amplitudes, and the T's are the total dipolar pathway timings. For this signal we can again design an approximate kernel like above to directly relate the distance distribution to the multi-spin multi-pathway signal: 

<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{120}&space;\fn_phv&space;\\\\&space;K_3^{MP}&space;=&space;\sum^3_{i=1}\sum^3_{j\neq&space;i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_mK(T_m,r)K(T_n,r)&space;\\\\&space;\text{for&space;which}&space;\\\\&space;F_3^{MP}&space;\approx&space;K_3^{MP}\sum^3_{i=1}a_iP_i(r)" target="_blank"><img src="https://latex.codecogs.com/png.latex?\dpi{120}&space;\fn_phv&space;\\\\&space;K_3^{MP}&space;=&space;\sum^3_{i=1}\sum^3_{j\neq&space;i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_mK(T_m,r)K(T_n,r)&space;\\\\&space;\text{for&space;which}&space;\\\\&space;F_3^{MP}&space;\approx&space;K_3^{MP}\sum^3_{i=1}a_iP_i(r)" title="\\\\ K_3^{MP} = \sum^3_{i=1}\sum^3_{j\neq i}\sum^M_{m=1}\sum^M_{n=1}\lambda_n\lambda_mK(T_m,r)K(T_n,r) \\\\ \text{for which} \\\\ F_3^{MP} \approx K_3^{MP}\sum^3_{i=1}a_iP_i(r)" /></a>

For which the same approximations hold as above, each pathway is properly simulated, except those where two different frequencies are coupled. Again, the description is exact for an equilateral geometry and deteriorates with increasing scalene geometry. With this, we could (approximately) fit any kind of DEER signal in any multi-spin system (e.g. 5-pulse DEER of a tetra-radical).

Are there any objections to implementing this approach @gjeschke and @stestoll ?

**Comment by stestoll** [comment]
I would suggest implementing this in DeerLab only after a careful review of all assumptions that went into these expressions, and an additional thorough experimental validation.
