### ISSUE TITLE
Memory and performance issues of sensitivan

### ISSUE THREAD

**Issue by luisfabib** [luisfabib/DeerAnalysis2#15]
Running a sensitivity analysis with a large multi-level full factorial setup, generates so many evaluation vectors that memory becomes an issue. 

For a run with 6 factors (each with 5 levels), at  the end of the analysis 65536 evaluations are generated and memory consumption reaches 5-6 GB. 

This can seriously slow-down calculation or even freeze some machines. 

An improved memory allocation system should be implemented.

**Comment by luisfabib** [comment]
A short benchmark reveals that the free version of built-in function of DeerLab  ``percentile`` is much more slower than the MATLAB built-in version ``prctile``. Thus, as the sensitivity analysis gets longer, the prctile function starts consuming more time.

![untitled](https://user-images.githubusercontent.com/48292540/74040997-1e106f80-49c5-11ea-9b7f-34ba5647bb61.png)


Profiling a sensitivity analysis of 64 combinations reveals that the ``percentile`` function evaluation is the second slowest part (6.47s total time).

**Comment by stestoll** [comment]
One way to deal with the performance issue is to recalculate percentiles not after every evaluation, but only after `N` (and after the last). `N`=10 would be reasonable. If the user requests plotting, `N` could be set to 1.

**Comment by luisfabib** [comment]
Evaluating the costly ``percentile`` function every *M* iterations does indeed yield a significant boost in performance (see figure)

![untitled](https://user-images.githubusercontent.com/48292540/74138570-24cffa00-4bf2-11ea-8cb2-adb4baae1309.png)

The performance boost is significant for *M*=10, still by using *M*=15 another boost in performance is achieved without hindering any possible updating of plots or diplays. 

The changes in 7f9ad346794bc551c058036d188335988df9d62e  represent a big leap forward in terms of performance. However, there might be other possible sources of performance issues to be fixed. Also, the memory issues are not solved by this. Thus, the issue remains open.

**Comment by luisfabib** [comment]
The ``percentile`` implementation is sub-optimal as it relies on multiple nested anonymous functions (which not always very time-efficient in MATLAB). Implemented another ``percentile`` function.
The performance of these functions were benchmarked using the ``tic toc`` function for different inputs always computing the percentile along the last dimension of the N-dimensional array.

| Input  | ``prctile`` | ``percentile`` (old) | ``percentile`` (new) |
| ------------- | ------------- | ------------- | ------------- |
| ``rand(500,1)`` | 0.004s | 0.001  | 0.001s |
| ``rand(500,500)`` | 0.067s | 0.126s  | 0.011s |
| ``rand(500,25000)`` | 0.246s | 0.461s  | 0.227s |
| ``rand(300,50000)`` | 0.307s | 0.777s  | 0.292s |
| ``rand(300,500,10)``  | 0.152s  | 10.463s | 0.168s  |
| ``rand(300,300,300)``  | 0.298s  | 7.50s | 0.296s  |

Using this faster (free) implementation of the percentile function will make the evaluation (almost) as fast as the toolbox version, and make the overall performance of ``sensitivan`` improve by a significant amount for heavy analyses.

**Comment by luisfabib** [comment]
For a template case, where we would evaluate a sensitivity analysis of a Q-point distance distribution:
````matlab

r = linspace(rmin,rmax,Q);

factors.factor1 = linspace(level_1,level_M,M);
factors.factor2 = linspace(level_1,level_M,M);
factors.factor3 = linspace(level_1,level_M,M);

factors.factorN = linspace(level_1,level_M,M);

Pstats = sensitivan(@fcn,factors)
````
the memory costs of the full factorial sensitivity analysis would be as follows:

| Factors N | Levels M | Q = 100 | Q=500 | Q=800   |
|-----------|---------|------|------|-------|
|1 | 2 | 2 kB |  8 MB | 13MB |  
|1 | 5 | 4 kB |  20 kB |  32 kB |  
|1 | 10 |  8 kB | 40 kB |  64 kB |  
|5 | 2 | 20 kB | 100 kB |  160 kB |  
|5 | 5 | 3 MB | 13 MB |  20 MB |  
|5 | 10 | 80 MB | 400 MB |  640 MB |  
|10 | 2 | 1 MB | 4 MB |  7 MB |  
|10 |  5 |  7.81 GB | 36.4 GB |  58.2 GB |  
|10 | 10 | 7.45 TB | 37.2 TB |  59.6 TB |  

One can see how easily one can consume large amounts of memory with ```sensitivan```. Analysis with more than 10 factors and 5 levels are downright impossible as MATLAB does not have enough memory (in a 32GB RAM machine) to run.

**Comment by luisfabib** [comment]
These memory costs arise form the storage of all evaluated outputs into the ``evals`` variable of sensitivan. While this variable could be cleared if the user does not request it as an output, it is required for updating the statistical estimators, especially the median and percentiles which require a sorted list of all observations in order to compute their values (a.k.a order statistics). In contrast, the mean value is easily updated by keeping just the cumulative sum stored.  

My alternative proposal is to use the streaming or iterative algorithms for estimating these values. For example, for updating the percentiles/quantiles a dynamic estimator typically used in unsupervised neural networks is
````matlab
 cumadev = cumadev + abs(sample - quantile);
 eta = 1.5*cumadev/(i*i);
 quantile = quantile + eta * (sign(sample - quantile) + 2*p - 1);
````
While this is an estimator (as it does not use a full table to precisely compute the quantiles, a quick benchmark against the ``prctile`` function of MATLAB reveals that this iterative algorithm leads to good-enough results, without the need to store any previous samples. The following figure shows the absolute deviation between this iterative method and the ``prctile`` function.

![untitled](https://user-images.githubusercontent.com/48292540/75322645-7b386c00-5873-11ea-98a4-9289f53a2183.png)

Here is a close-up for smaller numbers of samples

![untitled](https://user-images.githubusercontent.com/48292540/75322969-306b2400-5874-11ea-8bae-36ef608149ae.png)

It is clear that for the sample sizes where memory becomes a huge issue, the error in the percentile estimation is negligible for DeerLab purposes. And while for smaller sample sizes, the error may not be that small, there memory is absolutely not an issue and can be computed by using the built-in DeerLab ``percentile`` function. This difference for small samples is probably due to the fact that ``prctile`` uses linear interpolation. 

Using the MATLAB ``memory`` function one could anticipate the memory costs of the sensitivity analysis and then decide whether to store the ``evals`` variable even if the user requests it.

**Comment by luisfabib** [comment]
Following this idea of using dynamic quantile estimators to save memory I have found that the dynamic P2 algorithm is best suited for our purposes. https://doi.org/10.1145/4372.4378

The algorithm is stores 5 key samples, and updates them dynamically while estimating the percentile. Therefore, the memory cost is reduced to 5 samples, which in no practical case will exceed the memory capacity of MATLAB. 

Another benchmark of random numbers between the dynamic estimator above, the new P2 algorithm and the ``prctile`` function using order statistics reveals that this algorithm performs very similarly to the ``prctile`` function when storing all samples. Even for low samples is the estimation very similar, allowing the general use of the P2-algorithm for all cases in ``sensitivan``. 

![untitled](https://user-images.githubusercontent.com/48292540/75335449-ceb5b480-5889-11ea-87e2-9079c9904efc.png)

While, the algorithm was originally designed for single-point samples, generalizing this to multiple dimension should not be a problem.

**Comment by stestoll** [comment]
The quantile mode (dynamic estimate vs. accurate) should be an option to the user. If not given, `sensitivan` should make a choice based on expected memory impact.
