### ISSUE TITLE
Possible bug in sensitivian

### ISSUE THREAD

**Issue by gjeschke** [luisfabib/DeerAnalysis2#19]
sensitivian crashes (in my case) when I analyze for a single factor (only noise vector):

Index exceeds array bounds.

Error in sensitivan (line 235)
                main(jj) = abs(evalmean(1) - evalmean(2));

It works, after commenting out Factors interaction analysis

**Comment by luisfabib** [comment]
The current unity tests of DeerLab run that section without encountering an error. 

To reproduce your findings please...

* ... provide a code snippet of your variable definitions and call of ``sensitivan``.

* ... report the DeerLab version (current release is 0.8.beta)

**Comment by gjeschke** [comment]
It is 0.8.beta.

I suspect that the problem is with a uniform factor vector:

factors.noise_level = nlev*ones(1,options.noise_trials);

If I declare a non-uniform vector (and don't actually use the values), it works. A uniform vector may clash with the idea of  'sensitivity analysis', but for a random process, such as white Gaussian noise, it does make sense to do statistics at the same noise level with several trials.

**Comment by luisfabib** [comment]
Good, thanks I'll look into it.

A recommendation for this kind of analysis (analyzing different noise realizations at same noise level) would be to vary the rng seed for example: 

```
varpar.noiserealization = 1:10;
sensitivan(@fcn,varpar);

function y = fcn(varpar)
    seed = varpar.noiserealization ;
    rng(seed)
    noise = rand(100,1);
    y = noise;
end
```

this should work (for the moment) without crashing and has the benefit of making your analysis reproducible between runs.
