### ISSUE TITLE
Link in documentation points to Bitbucket

### ISSUE THREAD

**Issue by spribitzer** [luisfabib/DeerAnalysis2#2]
Working with release 0.1-beta, I noticed that the link at the top of the documentation points to the bitbucket repository and not the github one.

![image](https://user-images.githubusercontent.com/12035048/67889491-32161c80-fb0c-11e9-86ca-6ffeccf597ac.png)

**Comment by luisfabib** [comment]
This was already changed to GitHub in release 0.2.beta and now the feature has been completely removed in commit 839586c due to broken link generation from RTD.
