### ISSUE TITLE
Uniform dimensionality for arrays

### ISSUE THREAD

**Issue by laenan8466** [luisfabib/DeerAnalysis2#20]
DeerLab is behaving unintuitive for processing arrays. Prefered orientation for arrays (horizontal or vertical) should be uniform over all functions. Especially output should be uniform.

Functions in DeerLab seem to prefer 1 x m (horizontal) arrays. There are some exceptions (just the ones I found till now):

- `correctzerotime` is sensitive to input array dimensions and will yield identical dimension.
- `td_strexp` (and maybe also other td_models) yields m x 1-array and is insensitve to input.  The `dipolarkernel` function is insensitive to input dimension of background.
- `fitregmodel` yields m x 1 array (vertical). This is reasonable, as `K * Pfit` should yield Vfit. Matrix multiplication is not possible with 1 x m array.

Possible solution: 

- I would prefer uniform dimension of output arrays. 
- It is useful, if functions accept both types of arrays as input (especially if it's an 'input' function).
- If 1 x m dimensionality is chosen (prefered by me), a utility function to convert distance probabilities `Pfit` and kernel `K` to a dipolar signal `Vfit` could be handy. This function handles the dimensionality of `Pfit`. (mockup code)
   ```matlab
   Vfit = utility_function(K,Pfit);
   ```

   ```matlab
   function Vh = utility_function(K,P)
      Pv = reshape(P,[length(P),1]); % make array vertical for matrix multiplication
      Vv = K*Pv; % matrix multiplication.
      Vh = reshape(Vv,[1,length(Vv)]); % make output array horizontal
   end
   ```

Maybe, current design was intentional and I didn't get the reason. In this case, please close this issue.

**Comment by stestoll** [comment]
This is indeed not consistent yet. MATLAB's unfortunate choice of representing 1D vectors as 2D arrays creates these dimensionality issues.

I prefer Nx1 (columns) to represent vectors. This way, code is more readable. E.g., matrix-vector products are simple (`K*P`) and scalar products look reasonable (`a.'*b`). The most important requirement is that things are as frictionless for the user as possible, i.e. minimize the need for the user to transpose vectors.

Here is a proposal, with this in mind:
1. *Pass-through dimensionality*: Functions that take vector inputs return vector outputs with the same dimensionality as the inputs: Rows in rows out, columns in columns out.
2. *Output default*: Functions should return column vectors if they don't have vector inputs, or if they are called with two vector inputs with conflicting dimensionality (e.g. one column and one row).
3. *Implementation*: Internally, handle all vectors as column vectors.

**Comment by stestoll** [comment]
Here is a way to make a function input dimensionality agnostic:

```matlab
function V = myfun(P,X,K)
rowout = isrow(P) && isrow(X);  % row output if all input vectors are rows
if isrow(P), P = P.'; end
if isrow(X), X = X.'; end
V = K*P + X;                    % or any other set of matrix-vector operations
if rowout, V = V.'; end
```

**Comment by laenan8466** [comment]
> The most important requirement is that things are as frictionless for the user as possible, i.e. minimize the need for the user to transpose vectors.

I would totally agree, that this is most important.

> I prefer Nx1 (columns) to represent vectors. This way, code is more readable. E.g., matrix-vector products are simple (K*P) and scalar products look reasonable (a.'*b).

This is fine for me, as long as it is uniform.

> Here is a proposal, with this in mind:
> 
>     1. _Pass-through dimensionality_: Functions that take vector inputs return vector outputs with the same dimensionality as the inputs: Rows in rows out, columns in columns out.
> 
>     2. _Output default_: Functions should return column vectors if they don't have vector inputs, or if they are called with two vector inputs with conflicting dimensionality (e.g. one column and one row).
> 
>     3. _Implementation_: Internally, handle all vectors as column vectors.

Sounds reasonable to me, but I have two comments:

- When frictionless usability is most important, I would enforce proability vectors `P` to be column vectors. This circumvents that the user faces errors when using the matrix-vector product `K*P`. In this case no pass-through dimensionality.
- Pass-through dimensionality could lead to cases, where the user has row and column vectors in the end (due to output default and/or internally implementation). This could lead to confusion.

With this in mind, one could think about dropping pass-through dimensionality and enforce column vector output (as default). What is your opinion? Is there a benefit of pass-through dimensionality, that I miss?

**Comment by luisfabib** [comment]
Another important argument for column vectors is that non-arithmetic operations on column vectors in MATLAB are faster than on row vectors.

Also *pass-through dimensionality* is a good yet dangerous idea.

Let's take the operation ``K*P``, where ``P`` needs to be a column. Many MATLAB vector constructors such as the ``linspace`` function generate row vectors. This means that users are gonna create time and distance vectors``t`` and ``r`` most probably as row vectors. Internally this is of course taken care of, but if we for example set the dimensionality of e.g. ``P = rd_onegaussian(r,par)`` to the one of the ``r`` vector, then ``P`` will be constructed as a row vector and trying to calculate ``K*P`` will fail. To be honest MATLAB dimensionality errors are a pain to treat if one does not know the default dimensionalities of basic MATLAB functions, so exposing such a basic operation like this to such an error would be a critical design flaw. 

Therefore I suggest that all functions return a default dimensionality, e.g.

    P = rd_onegaussian(r,par); % In: row -> Out: column
    V = K*P; 

 except for those functions which take a vector and return that same vector which should operate with pass-through dimensionality, e.g
                 
    t = correctzerotime(t); % In: row -> Out: row

**Comment by laenan8466** [comment]
> except for those functions which take a vector and return that same vector which should operate with pass-through dimensionality, e.g
> 
> ```
> t = correctzerotime(t); % In: row -> Out: row
> ```

I would favor to have column vector output for this case as well. Then 'everything' is uniform, after 'first contact' with DL.

**Comment by gjeschke** [comment]
By coincidence, I am just fighting with the same issue of DeerLab. I would also prefer column vectors throughout (although old DeerAnalysis had row vectors throughout). 

In my case, correctphase is the main problem. It converts the column vector provided by deerload to a row vector, whereas later functions convert back. Differences between V and Vfit thus become matrices.

**Comment by stestoll** [comment]
Ok, let's drop pass-through dimensionality. So:
1) _Column output default_: All functions return column vectors, even if input vectors are rows.
2) _Input dimensionality tolerance_: All functions work equally well with row and column vector inputs.
3) _Column implementation_: All relevant vectors are handled as columns internally. However, simple arrays used for loops, indexing, etc. can be rows.

**Comment by luisfabib** [comment]
To identify all functions with dimensionality issues I've added a new set of unity tests ``*_dimensionality`` which call the corresponding functions with all permutations of row/column inputs and controls that the output values are the same and that the output dimensionality is that of a column. 
````
=======================================================================
DeerLab Unity Test Suite                 17-Feb-2020 15:05:20
(Matlab 9.7.0.1261785 (R2019b) Update 3)
DeerLab location: D:\lufa\projects\DeerLab\DeerLab\tests
=======================================================================
apt_dimensionality                    direct      pass    
aptkernel_dimensionality              direct      failed  
backgroundstart_dimensionality        direct      pass    
correctphase_dimensionality           direct      failed  
correctscale_dimensionality           direct      crashed 
correctzerotime_dimensionality        direct      failed  
dipolarkernel_dimensionality          direct      crashed 
dipolarsignal_dimensionality          direct      pass    
fftspec_dimensionality                direct      failed  
fitbackground_dimensionality          direct      crashed 
fitmultigauss_dimensionality          direct      pass    
fitparamodel_dimensionality           direct      failed  
fitregmodel_dimensionality            direct      pass    
longpass_dimensionality               direct      failed  
noiselevel_dimensionality             direct      failed  
obir_dimensionality                   direct      crashed 
regparamrange_dimensionality          direct      failed  
selectmodel_dimensionality            direct      crashed 
selregparam_dimensionality            direct      crashed 
sensitivan_dimensionality             direct      failed  
time2dist_dimensionality              direct      failed  
time2freq_dimensionality              direct      failed  
whitegaussnoise_dimensionality        direct      failed  
winlowpass_dimensionality             direct      crashed 
-----------------------------------------------------------------------
 5 passes,  12 failures,  7 crashes
-----------------------------------------------------------------------
````

I can see that the dimensionality issue is more extended than I thought, whereas for the built-in parametric models, the dimensionality is controlled in the ``*models_*``  unity test set introduced not too long ago. 
````
=======================================================================
DeerLab Unity Test Suite                 17-Feb-2020 15:07:23
(Matlab 9.7.0.1261785 (R2019b) Update 3)
DeerLab location: D:\lufa\projects\DeerLab\DeerLab\tests
=======================================================================
models_rd_onegaussian                 direct      pass    
models_rd_onerice                     direct      pass    
models_rd_randcoil                    direct      pass    
models_rd_shell                       direct      pass    
models_rd_shellshell                  direct      pass    
models_rd_shellsphere                 direct      pass    
models_rd_shellvoidshell              direct      pass    
models_rd_shellvoidsphere             direct      pass    
models_rd_sphere                      direct      pass    
models_rd_spherepoint                 direct      pass    
models_rd_spheresurf                  direct      pass    
models_rd_threerice                   direct      pass    
models_rd_twogaussian                 direct      pass    
models_rd_tworice                     direct      pass    
models_rd_wormchain                   direct      pass    
models_rd_wormgauss                   direct      pass    
-----------------------------------------------------------------------
 16 passes,  0 failures,  0 crashes
-----------------------------------------------------------------------
````
These all pass, so the dimensionality of the parametric models is working as should. 


I will fix the failing/crashing functions to solve all dimensionality issues in DeerLab.

**Comment by luisfabib** [comment]
Dimensionality issues have been fixed throughout. All functions now are agnostic with respect of the vector dimensionality (row/column) and they return column vectors as outputs. All tests from the dimensionality set are passing.

````
=======================================================================
DeerLab Unity Test Suite                 17-Feb-2020 17:09:24
(Matlab 9.7.0.1261785 (R2019b) Update 3)
DeerLab location: D:\lufa\projects\DeerLab\DeerLab\tests
=======================================================================
apt_dimensionality                    direct      pass    
aptkernel_dimensionality              direct      pass    
backgroundstart_dimensionality        direct      pass    
correctphase_dimensionality           direct      pass    
correctscale_dimensionality           direct      pass    
correctzerotime_dimensionality        direct      pass    
dipolarkernel_dimensionality          direct      pass    
dipolarsignal_dimensionality          direct      pass    
fftspec_dimensionality                direct      pass    
fitbackground_dimensionality          direct      pass    
fitmultigauss_dimensionality          direct      pass    
fitparamodel_dimensionality           direct      pass    
fitregmodel_dimensionality            direct      pass    
longpass_dimensionality               direct      pass    
noiselevel_dimensionality             direct      pass    
obir_dimensionality                   direct      pass    
regparamrange_dimensionality          direct      pass    
selectmodel_dimensionality            direct      pass    
selregparam_dimensionality            direct      pass    
sensitivan_dimensionality             direct      pass    
time2dist_dimensionality              direct      pass    
time2freq_dimensionality              direct      pass    
whitegaussnoise_dimensionality        direct      pass    
winlowpass_dimensionality             direct      pass    
-----------------------------------------------------------------------
 24 passes,  0 failures,  0 crashes
-----------------------------------------------------------------------
````
