### ISSUE TITLE
making the default branch 'develop' in the repository settings

### ISSUE THREAD

**Issue by spribitzer** [luisfabib/DeerAnalysis2#36]
As the branch for new features and that is being worked on is `development`, maybe it would make sense set `development` as the default branch in the repository settings? 

I can see three benefits:
- It would help outside contributors with nagivation (PRs would by default point to `development`)
- forks would automatically take `development` as starting branch (contributors would not accidentally start branching from a not up-to-date branch)
- and maybe most importantly, the branch presented on the front page would be  `development` instead of master, making it a lot easier to grasp what has been going on in the repository and seeing the newest commits

**Comment by luisfabib** [comment]
I know. I had been pushing this on my todo list. The ``develop`` branch is now the default.
