### ISSUE TITLE
Random-coil model: segment length

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#40]
Currently, the random-coil distribution model `rd_randcoil` [(here)](https://github.com/luisfabib/deerlab/blob/develop/functions/models/rd_randcoil.m) has a hard-wired segment length `R0 = 0.198` that cannot be changed.

The segment length should be a model parameter: `rd_randcoil(r,[N R0 nu]` or `rd_randcoil(r,[N nu R0]`.

**Comment by luisfabib** [comment]
I added the segment length as a model parameter. 

 For the defaults, I chose:  
- Start value: 0.2nm (similar to DeerAnalysis)
- Lower bound: 0.1nm (an estimation based on Fitzkee and Rose's [paper](https://www.pnas.org/content/101/34/12497)) 
- Upper bound: 0.4nm (based on the amino acid contour length measured by Ainavarapu SR et al. [here](https://doi.org/10.1529/biophysj.106.091561)).
