### ISSUE TITLE
Geometric basis of Rice distribution model is unclear

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#42]
Take two spin labels A and B with 3D Gaussian spatial distributions. The distribution of the distance between the two labels is not quite equal to `rd_onerice`, as shown in the example below.

Is `rd_onerice` representing a different geometric situation, or does `rd_onerice` need to be adjusted?

```matlab
clear, clc, clf

% Parameters for two 3D Gaussian distributions
rA0 = [0;0;0];
sigA = 1;
rB0 = [0;0;1];
sigB = 1;

% Monte Carlo simulation of norm of distance between A and B
N = 10e6;
rA = rA0 + randn(3,N)*sigA;
rB = rB0 + randn(3,N)*sigB;
rAB = vecnorm(rA-rB);

% Calculate PDF
r = linspace(0,8,201).';
dr = r(2)-r(1);
P0 = histcounts(rAB,[r; r(end)+dr]).';
P0 = P0/sum(P0)/dr;

% Fit rd_onerice to the obtained PDF
fun = @(p,r)rd_onerice(r,p);
mu = 1.92;
sig = 1.15;
p0 = [1.92 1.15];
pfit = lsqcurvefit(fun,p0,r,P0);
P1 = rd_onerice(r,pfit);
hold on

% Plotting
plot(r,P0,r,P1);
legend('3D Monte Carlo','rd_onerice','Interpreter','none');
box on
grid on
xlabel('r (nm)');
ylabel('P (nm^{-1})');
```

**Comment by luisfabib** [comment]
This deviation seems to appear for Ricians containing short distances, e.g. if instead of ``rB0 = [0;0;1];`` I set ``rB0 = [0;0;5];``. The ``rd_onerice`` model nicely fits the Monte-Carlo simulation.

**Comment by luisfabib** [comment]
I benchmarked DeerLab's ``dd_onerice`` against the Rician PDF computed from the Statistics and Machine Learning toolbox of MATLAB. 

```` matlab
clear,clc,clf 

r = linspace(0,6,500);
dr = mean(diff(r));

v = 2;
s = 0.9;
P1 = dd_onerice(r,[v s]);
P2 = pdf('Rician',r,v,s);

P1 = P1/sum(P1)/dr;
P2 = P2/sum(P2)/dr;

subplot(211)
plot(r,P1,r,P2)
axis tight, grid on
xlabel('r [nm]')
ylabel('P(r) [nm^-1]')
legend('DeerLab','Statistics Toolbox')
subplot(212)
plot(r,P1-P2.')
axis tight, grid on
xlabel('r [nm]')
ylabel('P(r) [nm^-1]')
legend('difference')
````
![untitled](https://user-images.githubusercontent.com/48292540/77165508-bc0e5400-6ab2-11ea-9894-b57b41fe7254.png)

and the results clearly show that the Rician distribution of DeerLab is very precise. I do not know exactly why the deviation appears when computed the PDF from those of Gaussian distributions. In any case the math behind the Rician distribution is correct and is working appropriately

.

**Comment by stestoll** [comment]
For DEER, we need the 3D generalization of the standard 2D Rice distribution. The paper [here](https://doi.org/10.1016/j.jmr.2010.10.005) has an expression. Mathematica documentation [here](https://reference.wolfram.com/language/ref/RiceDistribution.html) shows that for 3D (n = 3)we need the Norton-Rice distribution with m = n/2 = 3/2.

Of course, this needs to be checked against the Monte Carlo simulation above.

**Comment by luisfabib** [comment]
Since the paper cited in [here](https://www.sciencedirect.com/science/article/pii/S1090780710003228?via%3Dihub) is an old textbook without any apparent digital copy I could not check their references. The Norton-Rice distribution seems not to be exactly what we are looking for. 

I went another way and found out that a N-dimensional Rician distribution can be modeled by a non-central Chi-squared distribution. 

![CodeCogsEqn](https://user-images.githubusercontent.com/48292540/77319041-6a620580-6d0e-11ea-9817-071c55067080.png)


I compared this to the Monte-Carlo simulation and my results are: 

- the best fit can be obtained by a non-central Chi-squared distirbuition with L=1.5 which would resemble the equation in the paper above. 
- the case L=1 matches the 2D Rician distribution (as it should) 

![untitled](https://user-images.githubusercontent.com/48292540/77299589-fcf1ad00-6cec-11ea-8ba5-d5640c31a25a.png)

Here is the code snippet I used to make this figure: 

```` matlab
clear, clc, clf

sig = 0.5;
nu = 0.6;
% Parameters for two 3D Gaussian distributions
rA0 = [0;0;0];
sigA = sig;
rB0 = [0;0;nu];
sigB = sig;

% Monte Carlo simulation of norm of distance between A and B
N = 50e6;
rA = rA0 + randn(3,N)*sigA;
rB = rB0 + randn(3,N)*sigB;
rAB = vecnorm(rA-rB);

% Calculate PDF
r = linspace(0,4,201).';
dr = r(2)-r(1);
P0 = histcounts(rAB,[r; r(end)+dr]).';
P0 = P0/sum(P0)/dr;

% Fit rd_onerice to the obtained PDF
fun = @(p,r)dd_onerice(r,p);
nonchi = @(r,L,mu,sig) mu^(L-1)./(sig^2)*r.^L.*exp(-(r.^2+mu^2)/(2*sig^2) + mu*r/sig^2).*besseli(L-1,mu*r/sig^2,1);
fun1 =  @(p,r)nonchi(r,1,p(1),p(2))/sum(nonchi(r,1,p(1),p(2)))/mean(diff(r)); 
fun2 =  @(p,r)nonchi(r,1.5,p(1),p(2))/sum(nonchi(r,1.5,p(1),p(2)))/mean(diff(r)); 
fun3 =  @(p,r)nonchi(r,2,p(1),p(2))/sum(nonchi(r,2,p(1),p(2)))/mean(diff(r)); 

mu = 1.92;
sig = 1.15;
p0 = [1.92 1.15];
pfit = lsqcurvefit(fun,p0,r,P0);
P1 = dd_onerice(r,pfit);

pfit = lsqcurvefit(fun1,p0,r,P0);
P2 = fun1(pfit,r);
pfit = lsqcurvefit(fun2,p0,r,P0);
P3 = fun2(pfit,r);
pfit = lsqcurvefit(fun3,p0,r,P0);
P4 = fun3(pfit,r);

% Plotting
subplot(211)
plot(r,P0,'k',r,P1,r,P2,'--',r,P3,r,P4,'linewidth',1.5);
legend('Monte-Carlo','DeerLab Rician','non-central \chi^2_1','non-central \chi^2_{1.5}','non-central \chi^2_{2}');
box on
grid on
xlabel('r (nm)');
ylabel('P (nm^{-1})');
subplot(212)
plot(r,P1-P0,r,P2-P0,'--',r,P3-P0,r,P4-P0,'linewidth',1.5);
legend('DeerLab Rician','non-central \chi^2_1','non-central \chi^2_{1.5}','non-central \chi^2_{2}');
box on
grid on
xlabel('r (nm)');
ylabel('P - P_{sim} (nm^{-1})');
````

**Comment by stestoll** [comment]
Indeed, the non-central chi distribution with three degrees of freedom [(wiki)](https://en.wikipedia.org/wiki/Noncentral_chi_distribution) is what we need.
