### ISSUE TITLE
Remove docs function

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#45]
I don't think this is needed. A few points:
- The function name is so generic that it might name clash with other toolboxes.
- It will be confusing for users to have to use `doc` for MATLAB functions (incl. toolboxes) and `docs` for DeerLab

I suggest removing `docs`. Users can bookmark the DeerLab doc folder in their web browser.

Also, access to the DeerLab documentation can be incorporated using [MATLAB's capabilities for custom documentation](https://www.mathworks.com/help/matlab/matlab_prog/display-custom-documentation.html)? It doesn't look like any of this (info.xml, helptoc.xml, etc.) is currently implemented for DeerLab.

**Comment by luisfabib** [comment]
Done. At the moment I do not see the need to link our documentation with the MATLAB interface. Maybe this could be added in the future, but with the online documentation I doubt this would be needed.
