### ISSUE TITLE
multipathway backgrounds are inaccessible 

### ISSUE THREAD

**Issue by luisfabib** [luisfabib/DeerAnalysis2#49]
Currently the background function for the multipathway models is computed internally in``dipolarkernel`` given a basis background function ``bg_model``. There is however, no way to access the multipathway background afterwards. 

@stestoll The question is whether ``dipolarkernel`` should return this as a second output or to have another function/model which will generate this given a background model and pathway info.

**Comment by stestoll** [comment]
In this context we also need to consider how to provide/return (1-lambda)*B, which is a quantity that is plotted frequently.

**Comment by luisfabib** [comment]
That's true, however the program fits and returns the ``Bfit`` without the lambda scaling. Since that is a plotting choice I believe that is something which should be done by the user given some ``lambdafit`` and given ``Bfit``. If our tutorials show this enough, it should not become an issue. However, having functions returning ``Bfit`` and others ``(1-lambda)*Bfit`` would create confusion.

**Comment by stestoll** [comment]
We could introduce a function `dipolarbackground` that builds the background function given the time axis, the background model, and the pathway info. Example:

```matlab
K = dipolarkernel(t,r,pathinfo)
B = dipolarbackground(t,bgmodel,pathinfo)
V = (K*P)*B; % or V = (K*B)*P;
```
Or `B` could be returned as second output of `dipolarkernel`.

**Comment by stestoll** [comment]
With `fitsignal`, I ran into this issue again. It would be very useful to have a separate function `dipolarbackground` that calculates the total background decay, from a background model and the experiment pathway info.
