### ISSUE TITLE
normalization in multi-pathway kernels 

### ISSUE THREAD

**Issue by luisfabib** [luisfabib/DeerAnalysis2#50]
@stestoll I see two issues with the current multi-pathway system in ``dipolarkernel``:

#### Normalization of the pathway amplitudes

At the moment there is a check during input parsing which enforces the sum over all dipolar pathway amplitudes to be smaller/equal one. 

````matlab
% Assert that amplitude of non-modulated pathways is not larger than 1
% (this must hold even if the unmodulated amplitude is negative)
if round(sum(lambda)+Lambda0,5)>1
    error('In pathinfo, the sum of all lambdas cannot be larger than 1.');
end
````

While this is accurate and follows the theory, in practice leads to two problems: 

- While it is easy to pass inputs respecting this property, during a fit it represents a non-linear inequality, which is incompatible with most specific fast/accurate solvers in DeerLab (except ``fmincon``, which requires a toolbox). 

- It makes sense to enforce this probability since these values are probabilities (or cosine-modulated probabilities) limited thus to a 0 to 1 range. However, if we think about them as amplitudes (and we even call them that way), it would make sense for them to be able to adapt any values, since the relative values are what make the difference. The values could be normalized into a relative scale internally.

Differences in absolute scales of the pathway amplitudes only lead to differences in the absolute scaling of the whole dipolar signal. Which leads me to the next issue... 

#### Normalization of the multi-pathway kernels

According to the multi-pathway theory, the dipolar signals do not necessarily follow ``V(t=0) = 1`` and can adapt values smaller than 1. Again, DeerLab's ``dipolarkernel`` simulates this accurately, but in practice introduces some problems as well: 

- Experimental signals are usually re-scaled during pre-processing such that ``V(t=0) = 1``  holds. If a multipulse DEER experiment is pre-processed this way, it would be impossible to fit with the current ``dipolarkernel`` since ``V(t=0) = 1`` is not possible. 

- The current system requires a scale parameter to be introduced (instead of re-scaling in pre-processing), which introduces another fit parameter making processing (especially in regularization) more complex.

- If the kernel was normalized such that ``K(t=0,r) = 1`` then all these issues would be avoided, and would also allow unbounded pathway amplitudes as described above. 
 
I would for a normalization of the kernel such as we had in the earlier iterations of ``dipolarkernel``.

**Comment by stestoll** [comment]
For new, we have the `'Renormalize'` option that is set to `true` by default.

**Comment by luisfabib** [comment]
All normalization issues have been solved and unnormalized cases are still accessible via options from the corresponding functions.
