### ISSUE TITLE
Tutorial Sensitivity Analysis

### ISSUE THREAD

**Issue by nwili** [luisfabib/DeerAnalysis2#52]
Not sure if you want issues regarding the website/tutorials here as well.

Here: https://luisfabib.github.io/deerlab/0.8.beta/examples/example_sensitivan_tikhonov_simple.html#example_sensitivan_tikhonov_simple

It says `[Pmed,Pup,Plo] = sensitivan(fcn,factors);`

which is not the output of the sensitivian function anymore, right?

`[stats,factors,evals] = sensitivan(...)`

**Comment by luisfabib** [comment]
The tutorials section for the are currently under development, but this was fixed on the [development version](https://luisfabib.github.io/deerlab/develop/examples/example_sensitivan_tikhonov_simple.html). Even this is no longer completely up-to-date with the latest commits, but should work.
