### ISSUE TITLE
Inconsistent parameter ordering in multi-component models

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#55]
The parameter ordering in multi-component models are inconsistent between the built-in models `dd_*` and the mixture models generated by `mixmodels`.

Example of a two-Gauss model:
`dd_gauss2`: `[r01 w1 r02 w2 a1]`
`mixmodels(@dd_gauss,@dd_gauss)`: `[a1 r01 w1 r02 w2]`

This should be made consistent.

Two main possibilities:
1. Put the amplitudes at the end, as in the built-in models: `[r01 w1 r02 w2 a1]`
2. Put each amplitude with the parameters of the corresponding model: `[r01 w1 a1 r02 w2]`

The second has the aesthetic advantage that all parameters for each component are grouped together, but the first would only require changes in `mixmodels`.

**Comment by luisfabib** [comment]
Here is an example which shows the complexity that led to this ordering: 

Example of mixing a two-Gauss model with a Rice model
``dd_gauss2``: ``[r01 w1 r02 w2 a1]``
``dd_rice``: ``[nu1 sigma1]``
``mixmodels(@dd_twogauss,@dd_onerice)``: ``[A1 r01 w1 r02 w2 a1 nu1 sigma1]``
where ``A1`` is the amplitude of the whole two-Gaussian model. 

Here the problem would persist independently of the possibilities: 
1. ``[r01 w1 r02 w2 a1 nu1 sigma1 A1]``
2. ``[r01 w1 r02 w2 a1 A1 nu1 sigma1]`` 

Putting the model amplitudes at the beginning makes it easier to locate without having to check the ``info`` structure.

**Comment by stestoll** [comment]
Here is an analsyis for a three-Gauss model, constructed in different ways. It appears that putting amplitudes in the "middle" i.e. right next to their respective basis functions, leads to the most consistent parameter ordering.

```matlab
% Amplitudes last
[  r1 w1    r2 w2   r3   w3  a1  a2]  % gauss3
[[ r1 w1    r2 w2   a1] [r3  w3] A1]  % mix_models gauss2+gauss
[[ r1 w1] [ r2 w2   r3   w3  a2] A1]  % mix_models gauss+gauss2
[[[r1 w1] [ r2 w2]  a1] [r3  w3] A1]  % nested mixmodels (gauss+gauss)+gauss
[[ r1 w1] [[r2 w2] [r3   w3] a2] A1]  % nested mix_models gauss+(gauss+gauss)

% Amplitudes middle
[  r1  w1  a1  r2  w2   a2  r3 w3]    % gauss3
[[ r1  w1  a1  r2  w2]  A1 [r3 w3]]   % mix_models gauss2+gauss
[[ r1  w1] A1 [r2  w2   a2  r3 w3]]   % mix_models gauss+gauss2
[[[r1  w1] a1 [r2  w2]] A1 [r3 w3]]   % nested mixmodels (gauss+gauss)+gauss
[[ r1  w1] A1 [[r2 w2]  a2 [r3 w3]]]  % nested mix_models gauss+(gauss+gauss)

% Amplitudes first
[a1  a2  r1   w1   r2 w2    r3 w3]    % gauss3
[A1 [a1  r1   w1   r2 w2]  [r3 w3]]   % mix_models gauss2+gauss
[A1 [r1  w1] [a2   r2 w2    r3 w3]]   % mix_models gauss+gauss2
[A1 [a1 [r1   w1] [r2 w2]] [r3 w3]]   % nested mixmodels (gauss+gauss)+gauss
[A1 [r1  w1] [a2  [r2 w2]  [r3 w3]]]  % nested mix_models gauss+(gauss+gauss)
```

**Comment by luisfabib** [comment]
Having the amplitudes in the middle seems indeed to be the most consistent and ordered way. I repeated the same exercise with the mixing of a 3-parameter model (e.g. dd_gengauss) and putting the amplitudes in the middel gives the only consistent scheme. 

```matlab
% Amplitudes last
[[[r1 w1 b1] [ r2 w2 b2]  A1] [r3  w3  b3] A2]  % nested mixmodels (gengauss+gengauss)+gengauss
[[ r1 w1 b1] [[r2 w2 b2] [r3  w3   b3] A1] A2]  % nested mix_models gengauss+(gengauss+gengauss)

% Amplitudes middle
[[[r1  w1 b1] A1 [r2  w2 b2]] A1 [r3 w3 b3]]   % nested mixmodels (gengauss+gengauss)+gengauss
[[ r1  w1 b1] A1 [[r2 w2 b2]  A2 [r3 w3 b3]]]  % nested mix_models gengauss+(gengauss+gengauss)

% Amplitudes first
[A1 [a1 [r1  w1   b1] [r2 w2 b2]] [r3 w3 b3]]   % nested mixmodels (gengauss+gengauss)+gengauss
[A1 [r1  w1  b1] [A2  [r2 w2 b2]  [r3 w3 b3]]]  % nested mix_models gengauss+(gengauss+gengauss)
````
