### ISSUE TITLE
Fit functions should return basic statistics

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#57]
All DeerLab fitting functions should automatically return fit statistics. These should include at least
- chi-square and reduced chi-square values
- AIC, AICc, and BIC values

The reduced chi-square can be used to assess goodness of fit, the AIC, AICc, and BIC can be used for model comparisons.

**Comment by luisfabib** [comment]
List of fit functions in DeerLab and their current state with respect of this issue:

- [x] `fitparamodel`
- [x] `fitregmodel`
- [x] `fitsignal`
- [x] `fitmultimodel`
- [x] `selectmodel` 
- [ ] `fitbackground`
- [ ] `obir`
- [ ] `apt`

It is not imperative to have this on the legacy functions, however, the rest of functions should provide this.
