### ISSUE TITLE
Function to estimate noise level

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#66]
Several functions that provide uncertainty quantification rely on the estimated noise standard deviation from the experimental data. It would be good to isolate the noise estimation into a function.

The function `estimnoise` could provide several methods for noise estimation:
- Standard deviation across scans of a 2D dataset.
- Standard deviation of imaginary part of 1D signal (after phasing).
- Standard deviation of (1D signal - smoothed signal), using a Savitzky-Golay filter or a lowpass filter.
- Standard deviation of 1D signal from a provided model signal.

This could be a private function, or it could be public.

**Comment by luisfabib** [comment]
Currently there is a public function `noiselevel` which estimates the noise standard deviation. This function should be expanded to include the options listed above.

**Comment by luisfabib** [comment]
The second option in your list: 
- Standard deviation of imaginary part of 1D signal (after phasing).
does not need any dedicated implementation as it can be (probably more intuitively) obtained as follows: 
```matlab
[Vre,Vim] = correctphase(V);
std_re = noiselevel(Vre);
std_im = noiselevel(Vim);
```
