### ISSUE TITLE
dipolarkernel fails for long evolution times

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#7]
The following script produces a plot that is correct for the shorter trace, but wrong for the (minimally) longer one.

```matlab
clear, clc, clf

r = 3; % nm
tmax = 30; % us
dt = 0.05; % us

t1 = 0:dt:tmax; % us
t2 = 0:dt:tmax+dt; % us

S1 = dipolarkernel(t1,r);
S2 = dipolarkernel(t2,r);

plot(t1,S1,t2,S2);
```

**Comment by luisfabib** [comment]
The achieve a unit agnostic system the heuristics as of the current version determine whether a time axis is nanoseconds or microseconds by the criterion tmax<=30 as described in the [documentation](http://deeranalysis.org/tutorial.html). 

The current way to operate in time regimes beyond the heuristics is to specify the units via the [specunits](http://deeranalysis.org/api/specunits.html) function.

The script runs correctly if this function is used prior to the dipolar kernel construction. 

    clear, clc, clf
     r = 3; % nm
    tmax = 30; % us
    dt = 0.05; % us

    t1 = 0:dt:tmax; % us
    t2 = 0:dt:tmax+dt; % us

    t1 = specunits(t1,'us');
    t2 = specunits(t2,'us');

    S1 = dipolarkernel(t1,r);
    S2 = dipolarkernel(t2,r);

    plot(t1,S1,t2,S2);

The units system is still not definitive and may change in the stable release.
