### ISSUE TITLE
fitparamodel: remove non-least-squares algorithms

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#73]
Since `fitparamodel` solves a bounded least-squares problem, we should only have dedicated least-squares algorithms (`lsqnonlin` from the Optimization Toolbox, and `nlsqbnd` if the Optimization Toolbox is not available).

The solvers `fmincon`, `fminsearchcon`, and `fminsearch` should be removed.

This simplifies the interface and helps with maintenance.

**Comment by luisfabib** [comment]
I agree that we could get rid of `fmincon` and `fminsearch` without any loss, which would simplify the interface. 

However, due to Issue #74 the `fminsearchcon` solver is required as a toolbox-free alternative.
