### ISSUE TITLE
Start experiment models with ex_

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#77]
Right now, we use `exp_` as the prefix for all experiment models. I suggest to rename them to `ex_`. This would bring them in line with `dd_` and `bg_` (two letters each), and would not look like an exponential.

**Comment by luisfabib** [comment]
I know, the original reasoning for choosing `exp_`over `ex_` was that MATLAB has a wide range of examples named `ex_*` which could shadow DeerLab's models when searching for them.

**Comment by stestoll** [comment]
In which toolboxes do they occur? On my install (R2020a, with Opt.Tbx, Parallel Comp. Tbx., Stats&ML Tbx., Compiler), `ex_` - Tab on the command line doesn't give anything. In the MATLAB installation folder, there are a total of 5 files that start with `ex_` (3 m, 1 fig, 2 mat).

**Comment by luisfabib** [comment]
There are 32 example files starting with `ex_` in the DSP System toolbox (which I installed accidentally I think).

**Comment by stestoll** [comment]
Hmm, that's probably quite rare and shouldn't interfere with `ex_` models in DeerLab. I suggest we do the rename from `exp_*~ to `ex_*`.
