### ISSUE TITLE
Physical units heuristics system

### ISSUE THREAD

**Issue by luisfabib** [luisfabib/DeerAnalysis2#8]
Physical units are automatically detected based on numerical and physical heuristics. While they cover all experimental and common day situations, for method developers or for trial cases, the units system may not be optimal.

**Comment by stestoll** [comment]
Referring to #7, it makes not sense from a user perspective that (inferred) units change when going from `tmax=30` to `tmax=30.1`.

There are two solutions:
* fix the units throughout (microseconds; and either A or nm)
* provide the units as a global setting using the new Settings API (>=R2019b)

If possible, I prefer the first. It's less brittle, and more transparent to the user.

**Comment by luisfabib** [comment]
Units heuristics system has been deprecated in https://github.com/luisfabib/DeerAnalysis2/commit/bd2515f9932dd35738555ca93521cc09861a7da7. 

*Time*-domain variables have been set throughout to *microseconds* and *distance*-domain variables to *nanometers*.

This will avoid confusion and bugs in user-written scripts. Use of MATLAB preferences for global settings would introduce the need for documenting the user settings when sharing scripts.
