### ISSUE TITLE
Experiment models depend on t

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#84]
Currently, experiment models take the time axis `t` as their first input. Some of the models (such as `exp_5pdeer`) use this to set default parameter ranges for the refocusing times of secondary pathways, while other (such as `ex_4pdeer`) disregard it.

If the purpose of experiment models is to convert input parameters to the `pathinfo` structure, then I think they should be independent of `t`.

**Comment by luisfabib** [comment]
The `ex_models` must have some hard-coded starting values and bounds for the refocusing times of some dipolar pathways. Very good estimations of this starting values and boundaries can be inferred from `t`, especially the bounds.

I do not see right now a clean way to hard-code these boundaries without needing `t`, but ensuring that they still make physical sense. 

The alternative would be to let all refocusing times almost unbounded (e.g. all positive-valued times), with some numerically default starting value.

**Comment by stestoll** [comment]
There's an analogy to the distribution models here: Good estimates for the bounds for location parameters in `dd_` models would also depend on the `r` range. But for `dd_` models, we currently do not require `r` to be supplied for the `info = dd_mode()` call.
