### ISSUE TITLE
fitsignal select regularization parameter only with full input

### ISSUE THREAD

**Issue by laenan8466** [luisfabib/DeerAnalysis2#93]
# Possible Bug in `fitsignal` regularization parameter selection

## Reproduce
Start from the [Basic example](https://jeschkelab.github.io/DeerLab/0.9.0/examples/example_basicprocessing.html), changing the `Run fit` section:
```matlab
% Run fit
%-----------------------------------------------------------------------------
[Vfit,Pfit,Bfit,parfit,parci] = ...
    fitsignal(Vexp,t,r,'P',@bg_hom3dex,@ex_4pdeer,'RegParam','aic');
```

## Anticipated behavior
Fitsignal works as usual and uses the selectet criterion for alpha parameter selection. This corresponds to the [Additional Settings section in the documentation](https://jeschkelab.github.io/DeerLab/0.9.0/functions/fitsignal.html#fitsignal).

## Actual behavior / error
Error is raised:
```matlab
Error using parseoptional (line 70)
There is no 'aic' property on the fitsignal function

Error in fitsignal (line 112)
[regparam,regtype,alphaOptThreshold,TolFun] = parseoptional(optionalProperties,varargin);
```
It seems, that fitsignal anticipated `'aic'` as key for a key-value pair.

## Workaround
The function is working, when adding a empty value:
```matlab
% Run fit
%-----------------------------------------------------------------------------
[Vfit,Pfit,Bfit,parfit,parci] = ...
    fitsignal(Vexp,t,r,'P',@bg_hom3dex,@ex_4pdeer,'','RegParam','aic');
```
Possible reason could be, that the 'P' in the beginning is somehow seen as key for a key-value pair. I didn't investigated further.

**Comment by luisfabib** [comment]
The last input parameter in `fitsignal` is `par0` for the start values of the parameters (see Documentation). 

````matlab
[___] =  fitsignal(Vexp,t,r,'P',@bg_hom3dex,@ex_4pdeer,par0,'key',value)
````

Currently `fitsignal` has no parsening to identify input schemes where `par0` is skipped and the key-value pair is specified. That's why you example above works when passing `par0` empty.  

This parsening should be added in a future patch.

**Comment by laenan8466** [comment]
Oh yes, that makes sense. Thank you.
I misinterpreted the `fitsignal(___,'Key',Value)` in that way, any input form in advance is OK.

I propose closing.
