### ISSUE TITLE
Using DEERLab for 3-pulse or 2+1 pulse distance data

### ISSUE THREAD

**Issue by jsidabras** [luisfabib/DeerAnalysis2#94]
With the idea that the 3-pulse pathway should be identical to the 4-pulse pathway, is it sufficient to use `ex_4pulse` to study 3-pulse or 2+1 pulse experiments? Looking at the code, it is not clear to me where one would modify the experiment to be optimum for the "old" experiments.

**Comment by luisfabib** [comment]
Yes, it is sufficient to use the `ex_4pulse` experiment. This experiment model is the simplest one can have with just one modulated pathway as in 3-pulse or 2+1 experiments. 

This might need to be better specified in the documentation to avoid confusion.
